from typing import Optional, Dict, Any
from pydantic import BaseModel

class ErrorResponse(BaseModel):
    error: str
    message: str
    details: Optional[Dict[str, Any]] = None

class ErrorCode:
    # 세션 관련 에러
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_CREATE_FAILED = "SESSION_CREATE_FAILED"
    SESSION_UPDATE_FAILED = "SESSION_UPDATE_FAILED"
    SESSION_DELETE_FAILED = "SESSION_DELETE_FAILED"
    
    # 메시지 관련 에러
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_CREATE_FAILED = "MESSAGE_CREATE_FAILED"
    MESSAGE_UPDATE_FAILED = "MESSAGE_UPDATE_FAILED"
    MESSAGE_DELETE_FAILED = "MESSAGE_DELETE_FAILED"
    
    # 검색 관련 에러
    SEARCH_FAILED = "SEARCH_FAILED"
    EMBEDDING_ERROR = "EMBEDDING_ERROR"
    QDRANT_ERROR = "QDRANT_ERROR"
    
    # 시스템 에러
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"

    # 사용자 관련 에러
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_CREATE_FAILED = "USER_CREATE_FAILED"
    USER_UPDATE_FAILED = "USER_UPDATE_FAILED"
    USER_DELETE_FAILED = "USER_DELETE_FAILED"

    # Collection 관련 에러
    COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND"
    COLLECTION_ALREADY_EXISTS = "COLLECTION_ALREADY_EXISTS"
    COLLECTION_CREATE_FAILED = "COLLECTION_CREATE_FAILED"
    COLLECTION_UPDATE_FAILED = "COLLECTION_UPDATE_FAILED"
    COLLECTION_DELETE_FAILED = "COLLECTION_DELETE_FAILED"

    # Collection-User Link 관련 에러
    USER_ALREADY_IN_COLLECTION = "USER_ALREADY_IN_COLLECTION"
    LINK_ALREADY_EXISTS = "LINK_ALREADY_EXISTS" # Generic, for other integrity issues
    LINK_CREATE_FAILED = "LINK_CREATE_FAILED"
    LINK_DELETE_FAILED = "LINK_DELETE_FAILED"